# Generated by Django 5.1.6 on 2025-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_author_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="date_joined",
            field=models.DateField(auto_now=True),
        ),
    ]
